### ISSUE TITLE
Git repository in %temp% can get corrupted and cannot be reused

### ISSUE THREAD

**Issue by heetbeet** [VirtualActuary/zebra-vba-packager#13]
```
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "C:\Users\malan\Documents\2-Work\1-Auto-Actuary\develop\runner-engine\scripts\\zebra-import.py", line 15, in <module>
    Config(
  File "C:\Users\malan\anaconda3\lib\site-packages\zebra_vba_packager\zebra_config.py", line 121, in run
    git_download(link, source.temp_downloads, source.git_rev)
  File "C:\Users\malan\anaconda3\lib\site-packages\zebra_vba_packager\downloader.py", line 68, in git_download
    if is_on_ref(revision):
  File "C:\Users\malan\anaconda3\lib\site-packages\zebra_vba_packager\downloader.py", line 61, in is_on_ref
    commit = sh_lines([git, 'rev-parse', 'HEAD'])[0]
  File "C:\Users\malan\anaconda3\lib\site-packages\zebra_vba_packager\downloader.py", line 32, in sh_lines
    lst = subprocess.check_output(command,
  File "C:\Users\malan\anaconda3\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\malan\anaconda3\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Program Files\\Git\\mingw64\\bin\\git.exe', 'rev-parse', 'HEAD']' returned non-zero exit 
```

**Comment by heetbeet** [comment]
Same issue as #7

**Comment by heetbeet** [comment]
https://github.com/VirtualActuary/zebra-vba-packager/pull/16
