### ISSUE TITLE
util.get_matching_file_patterns should only return files not directories also

### ISSUE THREAD

**Issue by heetbeet** [VirtualActuary/zebra-vba-packager#27]
```
Traceback (most recent call last):
  File ".\importTemplateGeneratorBad.py", line 8, in <module>
    Config(
  File "C:\Users\simon\anaconda3\lib\site-packages\zebra_vba_packager\zebra_config.py", line 221, in run
    shutil.copy2(i, source.temp_transformed.joinpath(reli))
  File "C:\Users\simon\anaconda3\lib\shutil.py", line 432, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\simon\anaconda3\lib\shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\simon\\AppData\\Local\\Temp\\zebra-vba-packager\\e428f9cb-80321eb4-TemplateGenerator.git\\.git\\refs\\tags'
PS C:\Users\simon\devel\temp\realWorldExample>
```

**Comment by heetbeet** [comment]
High priority!
